apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 917024903431.dkr.ecr.us-east-1.amazonaws.com/jenkins:latest
        ports:
        - containerPort: 8080
