apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

vpc:
  id: "vpc-01b221e2b1809a1fb"
  subnets:
    private:
      us-east-1a: { id: "subnet-052cf6bcc682dd73c" }
      us-east-1b: { id: "subnet-0613913fffb0466b8" }

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    subnets:
      - "subnet-052cf6bcc682dd73c"
      - "subnet-0613913fffb0466b8"
