apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

vpc:
  id: "vpc-009d5c399664c1490"
  subnets:
    private:
      us-east-1a: { id: "subnet-05f03241a5f755939" }
      us-east-1b: { id: "subnet-098ffcc16e9aca9e3" }

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    subnets:
      - "subnet-05f03241a5f755939"
      - "subnet-098ffcc16e9aca9e3"
